-- ============================================================
--  HEPPLE — orders table (shared by site webhook + portal)
--  The Hepple site's Stripe webhook INSERTS rows here; the
--  portal READS them and UPDATES `fulfilled` / `fulfilled_at`.
--  Run once in Supabase → SQL Editor. Safe to re-run.
-- ============================================================

create table if not exists public.orders (
  id                      bigint generated by default as identity primary key,
  stripe_session_id       text unique not null,
  stripe_payment_intent   text,
  customer_email          text,
  customer_name           text,
  currency                text default 'gbp',
  subtotal                numeric(10,2),
  shipping                numeric(10,2),
  total                   numeric(10,2),
  item_count              integer default 0,
  items                   jsonb,
  cart_summary            text,
  posthog_distinct_id     text,
  shipping_address        jsonb,
  payment_status          text,
  fulfilled               boolean not null default false,
  fulfilled_at            timestamptz,
  created_at              timestamptz not null default now()
);

create index if not exists orders_created_at_idx on public.orders (created_at desc);
create index if not exists orders_fulfilled_idx  on public.orders (fulfilled);
create index if not exists orders_email_idx       on public.orders (customer_email);

-- Row Level Security ON, with NO anon/public policies.
-- The site webhook and the portal both use the SERVICE ROLE key,
-- which bypasses RLS. No browser ever reads this table directly.
alter table public.orders enable row level security;

-- ---- portal history upgrade (see migrations/2026_portal_history.sql) ----
alter table public.orders add column if not exists gift_message  text;
alter table public.orders add column if not exists has_gift_card boolean not null default false;
alter table public.orders add column if not exists source        text    not null default 'stripe';
create index if not exists orders_source_idx on public.orders (source);
